dock?

diff --git a/scripts/octoscreen b/scripts/octoscreen
--- a/scripts/octoscreen
+++ b/scripts/octoscreen
@@ -454,28 +454,38 @@ function octoscreen.prepare.remove(){
 function octoscreen.task.docker(){
     echo "Installing Docker...  This may take a while..."
     
-    local _curl='curl -fsSL'
+    local _docker="~/get_docker.sh"
     
-    [[ $VERBOSITY_CURRENT -ge $VERBOSITY_DEBUG ]] && _curl+='v'
-    
-    _curl+=' get.docker.com';
-    
-    [[ $VERBOSITY_CURRENT -lt $VERBOSITY_NOTICE ]] && {
-        _curl+=' 2>/dev/null'
-        _docker+=' > /dev/null 2>&1'
-    }
-    
-    echo.debug "Fetching Docker install '$_curl'"
-    
-    _docker=<( $_curl $_quiet )
-    
-    [[ $? -ne 0 || ! -f $_docker ]] && echo.fatal "Error fetching '$_docker'"
+    [[ ! -f $_docker ]] && {
+        
+        echo.notice "Fetching Docker Install Script"
+        
+        local _curl='curl -fsSL'
+        
+        [[ $VERBOSITY_CURRENT -ge $VERBOSITY_DEBUG ]] &&
+            _curl+='v';
+        
+        _curl+=' get.docker.com';
+        
+        [[ $VERBOSITY_CURRENT -lt $VERBOSITY_NOTICE ]] &&
+            _curl+=' > $_docker_file 2>/dev/null';
+        
+        echo.debug "Fetching Docker install '$_curl'"
+        
+        $_curl $_quiet
+        
+        [[ $? -ne 0 || ! -f $_docker ]] && echo.fatal "Error fetching '$_docker'"
+        
+    } || echo.notice "Docker Install Script exists, using that."
     
     echo.warn "If this hangs on 'Scanning something something something...' just hit enter, should be good..."
     
     declare -g CHANNEL='stable'
     declare -g DOWNLOAD_URL=''
     declare -g REPO_FILE=''
+    
+    [[ $VERBOSITY_CURRENT -lt $VERBOSITY_NOTICE ]] &&
+        _docker+=' > /dev/null 2>&1';
     
     sh $_docker
     
